### ISSUE TITLE
npm run dev的时候有问题？

### ISSUE THREAD

**Issue by lpove** [jrainlau/markcook#6]
npm run dev的时候有问题，报错。node和npm已经升级最新版本了，但是发现运行不了这个项目，在本地的其他vue+webpack项目都可以正常运行。

**Comment by lpove** [comment]
具体的cmd的报错您看看
`$ cnpm bugs markcook2.0
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\lpove\\AppData\\Roamin  g\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\lpo  ve\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.np  m.taobao.org" "bugs" "markcook2.0"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npm.taobao.org/markcook2.0
npm ERR! 404
npm ERR! 404  'markcook2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\program\new-learn\6th-vue.js\github\markcook\npm-debug.log
`

**Comment by zkaip** [comment]
我运行这个项目也有问题, 把 package.json 里 webpack-dev-server 改一下就好了
"webpack-dev-server": "2.1.0-beta.0"

**Comment by lpove** [comment]
运行npm run dev的时候报错

> markcook2.0@ dev /Users/panda/graduateProject/markcook
> webpack-dev-server --inline --hot

/Users/panda/graduateProject/markcook/node_modules/.2.2.1@webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolveLoader has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
    at webpack (/Users/panda/graduateProject/markcook/node_modules/.2.2.1@webpack/lib/webpack.js:19:9)
    at processOptions (/Users/panda/graduateProject/markcook/node_modules/.2.1.0-beta.0@webpack-dev-server/bin/webpack-dev-server.js:259:13)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! markcook2.0@ dev: `webpack-dev-server --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the markcook2.0@ dev script 'webpack-dev-server --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the markcook2.0 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs markcook2.0
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls markcook2.0
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/panda/graduateProject/markcook/npm-debug.log

**Comment by jrainlau** [comment]
@lpove @zkaip @thibautRe 
all the packages has been updated, and new feature of "service-worker supported" was enabled, take a try!
